name: CI
# test

on:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.name }} [ ${{ matrix.os }} ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
        toxenv: [test]
        toxargs: [-v]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
  
  test-aarch64:
    name: aarch64_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Install Python dependencies and Run tests
      run: |
           docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
           arm64v8/ubuntu:latest \
           bash -exc 'apt-get update && apt-get -y install python3 git python3-pip && \
           git submodule update --init --recursive && \
           pip3 install -U  pip && \
           pip3 install --upgrade tox && \
           tox -v -e test --'
  
